language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: heroku
  api_key:
    secure: CVWhiGrVVmrx0MG5p3WQKJFGf4LsdPI8Wb2pVBqRpKd0CYqCymR9D8TuVDgjN7XcLyYc9KebvZpnpLY0HqbOckrHp/Q0K3EaaoA8QWQSPQgK+L6KO1r8qv+s8q8BYNfbkSVwH14sFpPD7DXJ6aVTksyodaoHWsMzSWemRwAXFM2P7BSlkRpFPNPr58PguZcXTf0QvpdWJ///vh1v5GRWcM65MmQrlK8iXNfl6BU6cF2cVGDGW0/iLS3ll2IKqdiDjcDSQPu6wGMzA3hsfZZt9u2vXIwzXbtznr+y1MsJCrS+Li0N+VTEbmOms/v3iJap68j0MPzmzC61Q8XbbXiRUnejIbccIQ1IXWI93iQtkxLZu4GJFx7YxgYRT0Ong0hBHISRiOOevdmC7Ha14Iw+SqL5YZs0yCVSp6iXKPVrEVCcNsbLabVpQJ/OzcFwyox9nFg0xlwgve3y5J+i00bRkWShculDfwHpuyoOKfqlheqdaVCebAxoWvk1flDT3+uA3XH3DtxberrmKUQuTm8eIEYpdCm0cmOS+RRAM9tDEndBLGZAGUH9Stb/wxmYefAsovm7hwwN8IpOQRnsYpGvc6SQKosJm0lxuwmpic5xNSs19KikzmzTOUZi0ZdMArs1PbirVePo/GdGeMKm+l6cTxZQ/vG9JSPRfNmGJpuTcjI=
  app: mash-petitions
  on:
    repo: MashSoftware/petitions
    branch: master
